version: 2.1
orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.12
jobs:  
  lighthouse:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          awsAccessKeyId: $LIGHTHOUSE_CHECK_AWS_ACCESS_KEY_ID
          awsBucket: $LIGHTHOUSE_CHECK_AWS_BUCKET
          awsRegion: $LIGHTHOUSE_CHECK_AWS_REGION
          awsSecretAccessKey: $LIGHTHOUSE_CHECK_AWS_SECRET_ACCESS_KEY
          slackWebhookUrl: $LIGHTHOUSE_CHECK_SLACK_WEBHOOK_URL
          urls: 'http://jarf.me'
      - lighthouse-check/validate-status:
          minAccessibilityScore: '50'
          minBestPracticesScore: '50'
          minPerformanceScore: '50'
          minProgressiveWebAppScore: '10'
          minSeoScore: '50'
workflows:
  node-tests:
    jobs:
      - lighthouse
